### ISSUE TITLE
Compilation failed: cannot find IteratorUtil from org.neo4j.helpers.collection

### ISSUE THREAD

**Issue by rikwasmus** [neo4j-examples/neo4j-movies-java-bolt#1]
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project neo4j-movies: Compilation failure
.../projects/neo4j-movies-java-bolt/src/main/java/example/movies/backend/MovieService.java:[5,36] cannot find symbol
  symbol:   class IteratorUtil
  location: package org.neo4j.helpers.collection

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
```

```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by zqhxuyuan** [comment]
@rikwasmus you should change IteratorUtil on MovieService.java to Iterators.
and import org.neo4j.helpers.collection.Iterators; 
because IteratorUtil only on version 2.3.3, but it was remove on version 3.x

**Comment by jexp** [comment]
good find, I'll fix it

**Comment by jexp** [comment]
Fixed

**Comment by alchemistgo87** [comment]
@rikwasmus I am still not getting the package org.neo4j.helpers.collection.Iterators. I am using spring-data-neo4j:4.1.2.RELEASE

**Comment by jexp** [comment]
mvn clean install works for me on a clean checkout.

**Comment by alchemistgo87** [comment]
@jexp Did all the cleaning and refreshing, but its not showing the helpers package.
